### ISSUE TITLE
Investigate the range of the HRV

### ISSUE THREAD

**Issue by SiyuQian** [SiyuQian/Stress-recognition-project#4]
## Description
We have to find out what is the range of the normal HRV, then we could use the range to determine if a person is under pressure or having stress. 

## Todo
- [x] Read the source code from 'ppg_clean'
- [ ] Search in the databases for related literatures
- [ ] Comment/Document the research result

**Comment by SiyuQian** [comment]
https://support.ouraring.com/hc/en-us/articles/360025441974-An-Introduction-to-Heart-Rate-Variability
This is an article that we found might be useful for explaining the range of the HRV

**Comment by SiyuQian** [comment]
Closing this issue. As we are going to introduce an ML model to analyze the stress level. In the meantime, we found out that HRV value is highly related to the heart rate (heart rate goes up hrv goes down and heart rate goes down hrv goes up)
